### ISSUE TITLE
Hardcoded absolute path for Train.py

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/IGTD#2]
CANDLE_MODEL is just the name of the executable. Don't use absolute paths.
Look at lines 14 and 17 in https://github.com/JDACS4C-IMPROVE/Singularity/blob/develop/src/templates/train.sh for a solution.

https://github.com/JDACS4C-IMPROVE/IGTD/blob/a71f059ff492c7bcc6c7b58b4a2812c92f5cf82d/train.sh#L13

**Comment by zhuyitan** [comment]
Updated the code in develop branch. Please let me know if it still does not work.

**Comment by jonesse3** [comment]
@zhuyitan When trying to run your container in Polaris, I got an error: `/usr/local/bin/train.py` 
I noticed that `train.py` is different from the name of the file in your repo: `Train.py`. 
```
### Path to your CANDLEized model's main Python script###
CANDLE_MODEL=train.py
```

**Comment by wilke** [comment]
Make sure you are building from the improve branch of the model. The definiton files for polaris haven’t been updated yet.

On Sep 22, 2023, at 10:58 AM, Sara Jones ***@***.***> wrote:



@zhuyitan<https://github.com/zhuyitan> When trying to run your container in Polaris, I got an error: /usr/local/bin/train.py
I noticed that train.py is different from the name of the file in your repo: Train.py.

### Path to your CANDLEized model's main Python script###
CANDLE_MODEL=train.py

**Comment by jonesse3** [comment]
@wilke Thanks, I'll use the improve branch.

**Comment by wilke** [comment]
I am closing this issue. Planning and testing will restart from scratch for the next release.
