### ISSUE TITLE
Missing python model script in train.sh

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/IGTD#5]
Command: `singularity run /software/improve/images/IGTD.sif train.sh 0 /tmp --help`
Output: `No such file “/usr/local/bin/train.py`

Pointing to a non-existent train.py in train.sh.

**Comment by wilke** [comment]
I assume the correct name is IGTD_train_improve.py

@adpartin @zhuyitan Will change the name.

**Comment by adpartin** [comment]
@wilke I think you're right. @zhuyitan can you confirm?
